openapi: 3.1.0
info:
  version: 1.0.0
  title: SWAGGER CONTACTS
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This documentation for contacts
tags:
  - name: Contacts
    description: Operation with contacts
servers:
  - url: http://127.0.0.1:4000
paths:
  /contacts/{id}:
    get:
      $ref: ../swagger/path/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/path/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/path/contacts/{id}/delete.yaml
  /contacts:
    get:
      $ref: ../swagger/path/contacts/get.yaml
    post:
      $ref: ../swagger/path/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
